version: "3"

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./volume/data:/var/lib/mysql
    network_mode: host
    restart: always
